### ISSUE TITLE
Case looks closed, but spihelper thinks it's not

### ISSUE THREAD

**Issue by roysmith** [GeneralNotability/spihelper#40] opened 2021-05-18 15:07 UTC
https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/Gordimalo&oldid=1023727341

If you run More/SPI-Archive, you get:

Purged Wikipedia:Sockpuppet investigations/Gordimalo
Done!

If you run the interactive script, "Archive case" is greyed out.  I assume there's something broken in the markup that's not letting it be parsed properly, but I can't spot it.

**Comment by GeneralNotability** [comment] 2021-06-13 16:44
The case status was in the top-level section rather than the date-level section. I could add a check for this situation.

**Comment by GeneralNotability** [comment] 2021-06-13 17:15
Duplicate of #40.

**Closed by GeneralNotability** 2021-06-13 17:15 UTC
